=== doomtrooper/SaxXmlJavaParser/xmlToBeParsed/Trainee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com"
	elementFormDefault="qualified">

	<xs:element name="sapient-gmi">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="trainee" type="TraineeInfo" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="TraineeInfo">
		<xs:sequence>
			<xs:element name="personal-details" type="PersonalInfo"
				minOccurs="1" maxOccurs="1"></xs:element>
			<xs:element name="training-details" type="TrainingDetails"
				minOccurs="1" maxOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PersonalInfo">
		<xs:sequence>
			<xs:element name="name" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1" />
						<xs:pattern value="([a-zA-Z])*" />
						<xs:maxLength value="20" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="contact" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="10" />
						<xs:pattern value="([0-9])*" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="address" type="AddressInfo" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TrainingDetails">
		<xs:sequence>
			<xs:element name="stream" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Java" />
						<xs:enumeration value="DotNet" />
						<xs:enumeration value="QA" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="dateofjoining" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:date" />
				</xs:simpleType>
			</xs:element>
			<xs:element name="score" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="100" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AddressInfo">
		<xs:sequence>
			<xs:element name="housenumber" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1"></xs:minInclusive>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="street">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1"></xs:minInclusive>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="city" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" />
	</xs:complexType>

</xs:schema>

=== doomtrooper/SaxXmlJavaParser/xmlToBeParsed/Trainee.xml
<?xml version="1.0" encoding="UTF-8"?>
<sapient-gmi xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com Trainee.xsd ">
	<trainee>
		<personal-details>
			<name>Anan3d</name>
			<contact>8010140081</contact>
			<address type="current">
				<housenumber>96</housenumber>
				<street>7</street>
				<city>Gurgaon</city>
			</address>
			<address type="permanent">
				<housenumber>96</housenumber>
				<street>7</street>
				<city>Gurgaon</city>
			</address>
		</personal-details>
		<training-details>
			<stream>Java</stream>
			<dateofjoining>2015-01-05</dateofjoining>
			<score>77</score>
		</training-details>
	</trainee>

	<trainee>
		<personal-details>
			<name>Mounik</name>
			<contact>9999999999</contact>
			<address type="current">
				<housenumber>96</housenumber>
				<street>7</street>
				<city>Gurgaon</city>
			</address>
			<address type="permanent">
				<housenumber>96</housenumber>
				<street>7</street>
				<city>Gurgaon</city>
			</address>
		</personal-details>
		<training-details>
			<stream>Java</stream>
			<dateofjoining>2015-01-15</dateofjoining>
			<score>99</score>
		</training-details>
	</trainee>
</sapient-gmi>
